### ISSUE TITLE
misspelled words

### ISSUE THREAD

**Issue by jamcinnes2** [howweirdistheweather/weather_app#9]
Hey there is a misspelling on the web page. And a few in the source code that i've noticed. @katmai-mckittrick @hig314 

![Screenshot_20231019_183649](https://github.com/howweirdistheweather/weather_app/assets/60723350/26f2a031-310a-41a8-a59e-fb7595af4fab)

**Comment by mbjones** [comment]
Fixed before the 0.9.8 release.
